### ISSUE TITLE
how do i start this?

### ISSUE THREAD

**Issue by daguy2023** [Blasto33/CC-Turtle-Control-Panel#1]
im kinda new to programming, and i don't inderstand how to start this program. i used yarn to parse all required pakages, but how do i start this?

**Comment by Blasto33** [comment]
Hello! Thanks for the interest about my software.

It's a quite old project I had but according to my code, "yarn index.js" or just "npm start" should work perfectly.

However, please be aware that this is still in a very early state and only the web sockets work for now. I wouldn't advise you to try working on this, especially since you're a beginner but if you still want to give it a try, search for "websockets computercraft" and make a NodeJS server to interact with the CC: Tweaked WebSockets API. 

From here, you will be able to interact with turtles in your game and you will only have to create a front-end to make the interactions easier.

**Comment by daguy2023** [comment]
I found this fork of a script, https://github.com/PrintedScript/turtle-control
I just found this before I found the newer script.

anyways thanks for helping me get this running!

**Comment by Blasto33** [comment]
You're welcome! Have fun with your project!
